name: CI_Workflow

env:
 projekt: ${{GITHUB.WORKSPACE}} 

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  print_something:
    name: print_something
    runs-on: ubuntu-latest
    env:
      auto: Bmw
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
